import { describe, expect, it } from "vitest";
import { interestSelectionsRequestSchema, onboardingSchema, profileMediaRegistrationSchema, profileUpdateSchema, promptAnswersRequestSchema } from "./index";

describe("validation", () => {
  it("accepts standard email", async () => { const { emailSchema } = await import("./index"); expect(emailSchema.parse(" A@Example.com ")).toBe("a@example.com"); });
  it("rejects invalid phone", async () => { const { phoneSchema } = await import("./index"); expect(() => phoneSchema.parse("0771234567")).toThrow(); });
  it("requires display name length", () => { expect(() => profileUpdateSchema.parse({ displayName: "A" })).toThrow(); });
  it("accepts complete profile update", () => { expect(profileUpdateSchema.parse({ displayName: "Kay", bio: "Hello", socialStyles: ["low_pressure"], privacy: { discoverable: true, messagePermission: "everyone", storyVisibility: "connections", activityVisibility: "public" } }).displayName).toBe("Kay"); });
  it("rejects duplicate social styles", () => { expect(() => profileUpdateSchema.parse({ socialStyles: ["low_pressure", "low_pressure"] })).toThrow(); });
  it("rejects duplicate interests", () => { expect(() => interestSelectionsRequestSchema.parse({ interests: [{ interestId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa" }, { interestId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa" }] })).toThrow(); });
  it("limits interest count", () => { const interests = Array.from({ length: 13 }, (_, i) => ({ interestId: `aaaaaaaa-aaaa-4aaa-8aaa-${String(i).padStart(12, "0")}`, strength: 2 as const })); expect(() => interestSelectionsRequestSchema.parse({ interests })).toThrow(); });
  it("rejects duplicate prompt ids", () => { expect(() => promptAnswersRequestSchema.parse({ answers: [{ promptId: "one", answer: "a good answer" }, { promptId: "one", answer: "another good answer" }] })).toThrow(); });
  it("requires minimum onboarding data", () => { expect(() => onboardingSchema.parse({ displayName: "Kay", bio: "", socialStyles: ["text_first"], privacy: { discoverable: true, messagePermission: "everyone", storyVisibility: "connections", activityVisibility: "public" }, interests: [{ interestId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa" }], answers: [{ promptId: "p1", answer: "Hello there" }] })).toThrow(); });
  it("accepts complete onboarding payload", () => { const r = onboardingSchema.parse({ displayName: "Kay", bio: "Hello", socialStyles: ["text_first", "low_pressure"], privacy: { discoverable: true, messagePermission: "connections", storyVisibility: "connections", activityVisibility: "public" }, interests: [{ interestId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa" }, { interestId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb" }, { interestId: "cccccccc-cccc-4ccc-8ccc-cccccccccccc" }], answers: [{ promptId: "p1", answer: "Something I enjoy" }] }); expect(r.interests).toHaveLength(3); });
  it("rejects unsupported media type", () => { expect(() => profileMediaRegistrationSchema.parse({ kind: "avatar", storagePath: "u/a.jpg", thumbnailPath: "u/a-thumb.jpg", contentType: "image/gif", sizeBytes: 100, width: 100, height: 100, sortOrder: 0 })).toThrow(); });
  it("rejects media over 5MB", () => { expect(() => profileMediaRegistrationSchema.parse({ kind: "avatar", storagePath: "u/a.jpg", thumbnailPath: "u/a-thumb.jpg", contentType: "image/jpeg", sizeBytes: 5 * 1024 * 1024 + 1, width: 100, height: 100, sortOrder: 0 })).toThrow(); });
  it("rejects unsafe storage paths", () => { expect(() => profileMediaRegistrationSchema.parse({ kind: "avatar", storagePath: "../a.jpg", thumbnailPath: "u/a-thumb.jpg", contentType: "image/jpeg", sizeBytes: 100, width: 100, height: 100, sortOrder: 0 })).toThrow(); });
  it("accepts valid media metadata", () => { const r = profileMediaRegistrationSchema.parse({ kind: "avatar", storagePath: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa/a.jpg", thumbnailPath: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa/a-thumb.jpg", contentType: "image/jpeg", sizeBytes: 100, width: 1400, height: 1400, sortOrder: 0 }); expect(r.kind).toBe("avatar"); });
  it("accepts all supported visibility values", () => { expect(profileUpdateSchema.parse({ privacy: { discoverable: false, messagePermission: "nobody", storyVisibility: "private", activityVisibility: "public" } }).privacy?.discoverable).toBe(false); });
  it("rejects onboarding without a social style", () => { expect(() => onboardingSchema.parse({ displayName: "Kay", bio: "", socialStyles: [], privacy: { discoverable: true, messagePermission: "everyone", storyVisibility: "connections", activityVisibility: "public" }, interests: [{ interestId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa" }, { interestId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb" }, { interestId: "cccccccc-cccc-4ccc-8ccc-cccccccccccc" }], answers: [{ promptId: "p1", answer: "Something I enjoy" }] })).toThrow(); });
  it("rejects blank prompt answers", () => { expect(() => promptAnswersRequestSchema.parse({ answers: [{ promptId: "p1", answer: " " }] })).toThrow(); });
});
